name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'ticketing/infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubenetes cluster kubeconfig save ticketing
      - run: kubectl apply -f infra/k8s
